services:

  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    ports:
      - 5300:8080
    environment:
      - 'OLLAMA_BASE_URL=http://172.17.0.1:11434'
      - 'WEBUI_SECRET_KEY='
      - 'OAUTH_SCOPES=openid email profile'
      - 'OAUTH_CLIENT_ID=R83ODjRoTKnqCqSLmwfHvCHsomjuUcsHIc0IY9BD'
      - 'OAUTH_CLIENT_SECRET=0QW25kZVac8JZMChPX3Ff1ReC7sgVu8ISIUmfFF0WfiirS1bvLAbf3AxZp8CBsWu6jY0JtjVl9ZQmCfK2kwFoTVErY2dCTYjf33bnh0qY9Hv9ZVhSnYXSE2k9tR8xnXp'
      - 'OAUTH_PROVIDER_NAME=ADECOM Authentik'
      - 'OPENID_PROVIDER_URL=https://authentik.adecomsolutions.com/application/o/adecom-open-ai/.well-known/openid-configuration'
      - 'OPENID_REDIRECT_URI=https://ai.adecomsolutions.com/oauth/oidc/callback'
      - 'ENABLE_OAUTH_SIGNUP=true'
      - 'OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true'
      - 'WEBUI_URL=https://ai.adecomsolutions.com'
      - 'ENABLE_OAUTH_PERSISTENT_CONFIG=false'
      - 'WEBUI_AUTH_SIGNOUT_REDIRECT_URI=https://authentik.adecomsolutions.com/application/o/adecom-open-ai/end-session/'
      - 'ENABLE_LOGIN_FORM=false'
      - 'DEFAULT_USER_ROLE=user'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
